ip_address: "192.168.1.250"
sensor_x: 0.0
sensor_y: 0.0
sensor_z: 0.43
sensor_rx: 0.0
sensor_ry: 0.0
sensor_rz: 0.0
min_x: -50.0
max_x: 50.0
min_y: -50.0
max_y: 50.0
min_z: -4.0
max_z: 4.0
min_range: 0.0
max_range: 65.0
min_vertical_angle: -50.0
max_vertical_angle: 50.0
min_horizontal_angle: -180.0
max_horizontal_angle: 180.0
noise_filter_level: 10.0
